@ServiceA_HostAddress = http://localhost:6000

GET {{ServiceA_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ServiceA_HostAddress}}/api/test/getservice/
Accept: application/json

GET {{ServiceA_HostAddress}}/api/test/getServiceb1
Accept: application/json